name = "makerlog-ai"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MEMORY"
id = "199c353264d94cd394f58748ee5553f1"

[vars]
AGENT_NAME = "MakerLog"
AGENT_TONE = "helpful, technical, creative"
AGENT_AVATAR = "🔧"

[[kv_namespaces]]
binding = "CONFIDENCE"
id = "6ae44c11b6974c5cbac7ca36d80a2e90"
